### ISSUE TITLE
Adding "reset_all" test

### ISSUE THREAD

**Issue by coltonstaab1** [learn-co-curriculum/artist-song-modules#17]
I got stuck on test #5 for quite a while because it's not clear that you need to build the reset_all method before the count method for the count method test to pass. I think a test should be added after test #4 that makes sure that the reset_all method works before allowing you to move on as all other subsequent tests depend on it

**Comment by AnnJohn** [comment]
again thanks for raising this issue @coltonstaab1. We'll look into it as soon as we can.

**Comment by victhevenot** [comment]
Hey @coltonstaab1,

The `count` tests for both artists and songs doesn't depend on the `reset_all` method. The `reset_all` method does depend on `count`, but the tests prompt you to solve `count` first. I'm going to go ahead and close this issue. 

If you think it's still an issue, feel free to comment back with more info!
