### ISSUE TITLE
README needs work

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/artist-song-modules#19]
This is an awesome idea.  A hands-on trip around the "re-factoring" carousel.  Wonderful idea.

The teaching material to this point has not review defining a module inside a module, NOR how to retrieve a specific module from within an external module.  The syntax: "ModuleName::InnerModule" has never been mentioned or discussed to this point.

Also, the `.reset_all` methods are coded differently in Artist and Song.  Not sure if that's intentional or not.

**Comment by AnnJohn** [comment]
Hi @bhollan great feedback and thank you. We'll be updating our curriculum within the next month and will go through this again.

**Comment by victhevenot** [comment]
hey @bhollan - thanks so much for raising this issue. this material should be covered in the previous readme. I'm going to close this issue here and open it on the module readme.
