### ISSUE TITLE
Poor instructions

### ISSUE THREAD

**Issue by LSleutsky** [learn-co-curriculum/artist-song-modules#25]
The testing for this lab was causing a NameConstant uninitialized error when trying to extend the modules, with no explanation or assistance as to why. Somehow, I magically changed the order of the require_relative lines in the environment.rb file, and it got everything passing, but it did not say anything remotely close to that.

Initially, the environment.rb file was:

**require 'pry'

require_relative '../lib/artist.rb'
require_relative '../lib/song.rb'

require_relative '../lib/concerns/findable'
require_relative '../lib/concerns/memorable'
require_relative '../lib/concerns/paramable'**

And it was not even allowing me to use rspec because it kept throwing a NameConstant uninitialized error in terminal, with no clues as to how to correct it. But when I somehow accidentally changed the environment.rb file to:

**require 'pry'

require_relative '../lib/concerns/findable'
require_relative '../lib/concerns/memorable'
require_relative '../lib/concerns/paramable'

require_relative '../lib/artist.rb'
require_relative '../lib/song.rb'**

It started to work, and I was able to run my tests. Had I not accidentally changed the order, I would have never passed the test, nor would I even be able to get them to run, It's kind of silly to not include something along those lines to at least hint that the order of the require_relative lines will affect the program in its entirety. Wasted like 2 hours trying to figure out was wrong, knowing that everything I was doing was right. At least if there is an included file where the only requirements are to comment out certain lines when it is necessary to based on the steps, they should be written in order to begin with, or instruction should be given to change them around.

Thank you.

**Comment by AnnJohn** [comment]
hi @LSleutsky thanks for raising the issue. And sorry for the frustration. We'll look into this and update soon.
