### ISSUE TITLE
just confused about memorable module vs findable

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/artist-song-modules#33]
In the description of the Memorable module, it looks like we are supposed to define our find_by_name method there.  Then in the Findable module we do the same.  If we leave the method definition in the Memorable module we're duplicating code, are we just supposed to define the module for the first time in the Findable module?

Thanks!!
Happy 4th :us:

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
