### ISSUE TITLE
Reference to material from "past" exercise that is yet to come

### ISSUE THREAD

**Issue by marielfrank** [learn-co-curriculum/artist-song-modules#42]
"Remember our super keyword from the inheritance code along exercise?" references [this lab](https://learn.co/tracks/full-stack-web-dev-with-react/object-oriented-ruby/object-architecture/super) which is further along in the curriculum. Of course it's great to introduce the topic, but there's no way we can remember a codealong that we haven't gotten to yet.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We updated the lessons order. The `super` lesson and read me now precede this assignment.

As always, thanks for contributing! 💙
