### ISSUE TITLE
Might be helpful to include a note about using `self` when defining class methods 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/artist-song-modules#43]
@cjbrock 
I have had a few students confused about defining class methods in modules; many get confused about the omission of the `self` keyword. It may be helpful to emphasize that the `self` keyword is not needed when defining class methods in modules and that `extend` takes care of whether or not the methods defined in the module are used as class or instance methods.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We updated the readme to include the paragraph below.

`Remember that the self keyword is omitted when defining class methods inside modules. The extend keyword is responsible for defining the method as a class method vs. an instance method (which would use the include keyword).`

As always, thanks for contributing! 💙
