### ISSUE TITLE
self.reset_all and self.count are inconsistently defined in the Artist and Song methods.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/artist-song-modules#44]
Hello. Initially, the Song class has self.reset_all and self.count defined like this:

def self.reset_all
  @@songs.clear
end

def self.count
  self.all.count
end

Whereas the Artist class initially defines self.reset_all and self.count like this:

def self.reset_all
  self.all.clear
end

def self.count
  @@artists.count
end

The problem is that the README says that self.reset_all and self.count have the exact same code in both classes and can thus be put inside a module. The problem is, they are not the same. I don't know if that was intentional or not; perhaps the goal was to get students to figure out how those class methods could be refactored inside of one module. 

But to prevent confusion, I would like to suggest defining the #reset_all and #count methods inside of both classes like this:

def self.reset_all
  self.all.clear
end

def self.count
  self.all.count
end

Thank you (as always) for looking into this issue.

Regards,

Sdcrouse

**Comment by sgharms** [comment]
Wow @Sdcrouse You're the first person to notice that in (.....uses `git blame`....) 4 years!

You're right, there's some additional cognitive drag here as there's additional overhead in the `Artist` implementation (to, in turn, to get to the next layer). I'll make the change here.

**Comment by sgharms** [comment]
Good catch, all done in commit 0943607

**Comment by Sdcrouse** [comment]
You're welcome! Happy to help.
