### ISSUE TITLE
environment.rb order specific

### ISSUE THREAD

**Issue by marysue** [learn-co-curriculum/artist-song-modules#46]
It sure would be nice if you put an instruction in your introduction to environment.rb that it is order specific! 

You say:

Open up the config directory and look at the environment.rb file. You'll see that we're already requiring the files that hold our Artist and Song class. Any additional files we make should be required by this environment.rb file.

I say be specific here:

Because the environment.rb file is read and loaded into memory in order, if Artist requires Memorable, then require Artist must come AFTER require Memorable.  Memorable must be loaded first, so that as Ruby when  loads Artist, Memorable::ClassInstances is already defined.  .

Example:

require_relative '../lib/concerns/memorable'  #Memorable::ClassInstances must be loaded before
                                                                        #referencing in artist.rb

require_relative '../lib/artist.rb'  #extend Memorable::ClassInstances referenced here.  If Ruby doesn't
                                                  #load memorable first, it will not know what this references
require_relative '../lib/song.rb'

**Comment by maxwellbenton** [comment]
Hi @marysue,

Thank you for spotting this and bringing this to our attention. I completely agree and have updated the this section based on your feedback. Thank you for contributing to a learn.co repository and helping future students!

If you don't feel this problem has been resolved, please reopen this issue.
